import { useEffect, useMemo, useState } from 'react';
import './components/styles/pages.css';

const API = 'http://localhost:3001';
const pages = ['overview', 'masterkeys', 'subkeys', 'logs', 'demo'];
const fmtNum = (n) => (n >= 1e6 ? `${(n / 1e6).toFixed(1)}M` : n >= 1e3 ? `${(n / 1e3).toFixed(1)}k` : String(n || 0));
const fmtTime = (ts) => (ts ? new Date(ts * 1000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) : '—');
const fmtDate = (ts) => (ts ? new Date(ts * 1000).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' }) : 'Never');
const quotaColor = (u, l) => ((u / l) * 100 > 90 ? 'over' : (u / l) * 100 > 70 ? 'warn' : 'ok');
const api = async (path, opts = {}) => (await fetch(API + path, { headers: { 'Content-Type': 'application/json', ...opts.headers }, ...opts, body: opts.body ? JSON.stringify(opts.body) : undefined })).json();

export default function App() {
  const [page, setPage] = useState('overview'); const [subkeys, setSubkeys] = useState([]); const [masterKeys, setMasterKeys] = useState([]); const [logs, setLogs] = useState([]); const [analytics, setAnalytics] = useState({});
  const [notif, setNotif] = useState(null); const [addOpen, setAddOpen] = useState(false); const [skOpen, setSkOpen] = useState(false); const [reveal, setReveal] = useState('');
  const [addKeyValue, setAddKeyValue] = useState(''); const [skForm, setSkForm] = useState({ name: '', provider: 'openai', limit: 50000, expiry: '' });
  const [demo, setDemo] = useState({ token: '', model: 'gpt-4o-mini', prompt: 'Say hello in exactly 5 words.', lines: [] });
  const notify = (m, t = 'success') => { setNotif({ m, t }); setTimeout(() => setNotif(null), 3000); };
  const loadOverview = async () => { const [sks, an] = await Promise.all([api('/api/subkeys'), api('/api/analytics')]); setSubkeys(sks); setAnalytics(an); setLogs(an.logs || []); };
  const loadMasterKeys = async () => setMasterKeys(await api('/api/master-keys'));
  const loadSubkeys = async () => setSubkeys(await api('/api/subkeys'));
  const loadLogs = async () => { const an = await api('/api/analytics'); setLogs(an.logs || []); };
  useEffect(() => { ({ overview: loadOverview, masterkeys: loadMasterKeys, subkeys: loadSubkeys, logs: loadLogs, demo: loadSubkeys }[page])?.(); }, [page]);
  const demoPreview = useMemo(() => demo.token ? `POST /v1/chat/completions\nAuthorization: Bearer ${demo.token.slice(0, 12)}••••••\n\n{\n  "model": "${demo.model}",\n  "messages": [{"role": "user", "content": "${demo.prompt}"}]\n}` : 'Select a subkey to see the request preview...', [demo]);
  return <div className='app'><aside className='sidebar'><div className='logo'><div className='logo-name'>KeyGate</div></div><nav className='nav'>{pages.map(p => <button key={p} className={`nav-item ${page === p ? 'active' : ''}`} onClick={() => setPage(p)}>{p}</button>)}</nav></aside><main className='main'><div className='page active'>
    {page === 'overview' && <div><h2 className='page-title'>Overview</h2><div className='stats'><div className='stat'><div className='stat-val'>{subkeys.filter(s => s.status === 'active').length}</div><div className='stat-label'>Active subkeys</div></div><div className='stat'><div className='stat-val'>{fmtNum(analytics.totalRequests)}</div><div className='stat-label'>Total requests</div></div><div className='stat'><div className='stat-val'>{fmtNum(analytics.totalTokens)}</div><div className='stat-label'>Tokens used</div></div><div className='stat'><div className='stat-val'>{analytics.avgLatency || '—'}</div><div className='stat-label'>Avg latency (ms)</div></div></div></div>}
    {page === 'masterkeys' && <div><h2 className='page-title'>Master keys</h2><button className='btn btn-primary' onClick={() => setAddOpen(true)}>+ Add key</button>{masterKeys.map(mk => <div className='card' key={mk.id}><b>{mk.provider}</b> {mk.key_masked} Added {fmtDate(mk.created_at)} <button className='btn btn-danger btn-sm' onClick={async () => { await api('/api/master-keys/' + mk.id, { method: 'DELETE' }); notify('Master key removed'); loadMasterKeys(); }}>Remove</button></div>)}</div>}
    {page === 'subkeys' && <div><h2 className='page-title'>Subkeys</h2><button className='btn btn-primary' onClick={() => setSkOpen(true)}>+ Create subkey</button><div className='card'><table><thead><tr><th>Name</th><th>Token</th><th>Quota</th><th>Actions</th></tr></thead><tbody>{subkeys.map(sk => <tr key={sk.id}><td>{sk.name}</td><td>{sk.token?.slice(0, 12)}••••{sk.token?.slice(-4)}</td><td><div className='quota-text'>{fmtNum(sk.tokens_used)} / {fmtNum(sk.monthly_token_limit)}</div><div className='quota-bar'><div className={`quota-fill ${quotaColor(sk.tokens_used, sk.monthly_token_limit)}`} style={{ width: `${Math.min(100, Math.round((sk.tokens_used / sk.monthly_token_limit) * 100))}%` }} /></div></td><td><button className='btn btn-danger btn-sm' onClick={async () => { await api('/api/subkeys/' + sk.id, { method: 'PATCH', body: { status: 'revoked' } }); loadSubkeys(); }}>Revoke</button></td></tr>)}</tbody></table></div></div>}
    {page === 'logs' && <div><h2 className='page-title'>Request logs</h2><div className='card'><table><tbody>{logs.map((l, i) => <tr key={i}><td>{fmtTime(l.created_at)}</td><td>{l.subkey_name}</td><td>{l.model}</td><td>{fmtNum(l.tokens_used)}</td><td>{l.latency_ms || '—'}ms</td><td>{l.status}</td></tr>)}</tbody></table></div></div>}
    {page === 'demo' && <div><h2 className='page-title'>Live demo</h2><select value={demo.token} onChange={(e) => setDemo({ ...demo, token: e.target.value })}><option value=''>— select a subkey —</option>{subkeys.filter(s => s.status === 'active').map(s => <option value={s.token} key={s.id}>{s.name}</option>)}</select><input value={demo.prompt} onChange={(e) => setDemo({ ...demo, prompt: e.target.value })} /><pre>{demoPreview}</pre><button className='btn btn-primary' onClick={async () => { const res = await fetch(API + '/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${demo.token}` }, body: JSON.stringify({ model: demo.model, messages: [{ role: 'user', content: demo.prompt }], max_tokens: 150 }) }); const data = await res.json(); notify(res.ok ? 'Request proxied — check logs for usage' : data.error?.message || 'Request failed', res.ok ? 'success' : 'error'); }}>Run test call →</button></div>}
  </div></main>
  {addOpen && <div className='modal-backdrop open'><div className='modal'><input placeholder='sk-...' value={addKeyValue} onChange={(e) => setAddKeyValue(e.target.value)} /><button className='btn btn-primary' onClick={async () => { await api('/api/master-keys', { method: 'POST', body: { provider: 'openai', api_key: addKeyValue } }); setAddOpen(false); setAddKeyValue(''); loadMasterKeys(); }}>Save encrypted key</button></div></div>}
  {skOpen && <div className='modal-backdrop open'><div className='modal'><input placeholder='name' value={skForm.name} onChange={(e) => setSkForm({ ...skForm, name: e.target.value })} /><button className='btn btn-primary' onClick={async () => { const sk = await api('/api/subkeys', { method: 'POST', body: { name: skForm.name, provider: skForm.provider, monthly_token_limit: Number(skForm.limit), expires_in_days: skForm.expiry ? Number(skForm.expiry) : null } }); setSkOpen(false); setReveal(sk.token || ''); loadSubkeys(); }}>Generate subkey</button></div></div>}
  {reveal && <div className='modal-backdrop open'><div className='modal'><div className='reveal-token'>{reveal}</div><button className='btn btn-primary' onClick={() => setReveal('')}>Done</button></div></div>}
  {notif && <div className={`notif show ${notif.t}`}>{notif.m}</div>}</div>;
}
